### ISSUE TITLE
Exception when serving /opensearch.xml

### ISSUE THREAD

**Issue by xavfernandez** [Polyconseil/dokang#11]
```
Dec 27 16:30:48 our.server.org docker[27484]: 2016-12-27 16:30:48,035 ERROR [waitress][waitress] Exception when serving /opensearch.xml
Dec 27 16:30:48 our.server.org docker[27484]: Traceback (most recent call last):
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
Dec 27 16:30:48 our.server.org docker[27484]: task.service()
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/waitress/task.py", line 169, in service
Dec 27 16:30:48 our.server.org docker[27484]: self.execute()
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
Dec 27 16:30:48 our.server.org docker[27484]: app_iter = self.channel.server.application(env, start_response)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/pyramid/router.py", line 242, in __call__
Dec 27 16:30:48 our.server.org docker[27484]: response = self.invoke_subrequest(request, use_tweens=True)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/pyramid/router.py", line 217, in invoke_subrequest
Dec 27 16:30:48 our.server.org docker[27484]: response = handle_request(request)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 21, in excview_tween
Dec 27 16:30:48 our.server.org docker[27484]: response = handler(request)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/pyramid/router.py", line 163, in handle_request
Dec 27 16:30:48 our.server.org docker[27484]: response = view_callable(context, request)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
Dec 27 16:30:48 our.server.org docker[27484]: result = view(context, request)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
Dec 27 16:30:48 our.server.org docker[27484]: response = view(request)
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/dokang/views.py", line 82, in opensearch
Dec 27 16:30:48 our.server.org docker[27484]: content_type=b'application/opensearchdescription+xml'
Dec 27 16:30:48 our.server.org docker[27484]: File "/home/dokang/venv/lib/python3.5/site-packages/webob/response.py", line 119, in __init__
Dec 27 16:30:48 our.server.org docker[27484]: if content_type and 'charset=' not in content_type:
Dec 27 16:30:48 our.server.org docker[27484]: TypeError: a bytes-like object is required, not 'str'
```

**Comment by dbaty** [comment]
Corrigé. Merci !
